services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5431:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      restart: always
      ports:
        - "5000:5000"
      depends_on:
        - db
      environment:
        - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@db:5432/postgres
  volumes:
    db-data:
