services:
  frontend:
    container_name: inventory_frontend
    image: inventory_frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    volumes:
      - ./client:/app
  backend:
    container_name: inventory_backend
    image: inventory_backend
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    container_name: inventory_postgres_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: inventory_postgres_db
    ports:
      - "5431:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
